import type {
  AccountBalance,
  ActivityEntry,
  Appointment,
  Campaign,
  ClinicEvent,
  ExpenseCategory,
  Invoice,
  NewsArticle,
  Patient,
  Payment,
  Service,
  StaffMember,
  Transaction,
  TrendPoint,
} from "./types";

/** The clinic's "today" inside the demonstration data set. */
export const DEMO_TODAY = "2025-09-20";
export const DEMO_TODAY_LABEL = "Sat, Sep 20, 2025";
export const CLINIC_HOURS = "8:00 AM – 5:00 PM";

export const staff: StaffMember[] = [
  {
    id: "STF-001",
    name: "Dr. James Mwangi",
    role: "DENTIST",
    title: "General Dentist",
    specialty: "General Dentistry",
    email: "james.mwangi@brightsmile.co.ke",
    phone: "+254 712 345 001",
    experienceYears: 8,
    rating: 4.8,
    reviews: 124,
    status: "AVAILABLE",
    department: "Clinical",
    avatarTone: "bg-info-soft text-info",
    initials: "JM",
  },
  {
    id: "STF-002",
    name: "Dr. Sarah Kimani",
    role: "DENTIST",
    title: "Cosmetic Dentist",
    specialty: "Cosmetic Dentistry",
    email: "sarah.kimani@brightsmile.co.ke",
    phone: "+254 712 345 002",
    experienceYears: 6,
    rating: 4.9,
    reviews: 98,
    status: "AVAILABLE",
    department: "Clinical",
    avatarTone: "bg-violet-soft text-violet",
    initials: "SK",
  },
  {
    id: "STF-003",
    name: "Dr. Peter Otieno",
    role: "DENTIST",
    title: "Restorative Dentist",
    specialty: "Restorative Dentistry",
    email: "peter.otieno@brightsmile.co.ke",
    phone: "+254 712 345 003",
    experienceYears: 10,
    rating: 4.7,
    reviews: 156,
    status: "AVAILABLE",
    department: "Clinical",
    avatarTone: "bg-teal-soft text-teal",
    initials: "PO",
  },
  {
    id: "STF-004",
    name: "Dr. Amina Hassan",
    role: "DENTIST",
    title: "Orthodontist",
    specialty: "Orthodontics",
    email: "amina.hassan@brightsmile.co.ke",
    phone: "+254 712 345 004",
    experienceYears: 7,
    rating: 4.8,
    reviews: 112,
    status: "AVAILABLE",
    department: "Clinical",
    avatarTone: "bg-success-soft text-success",
    initials: "AH",
  },
  {
    id: "STF-005",
    name: "Dr. David Ochieng",
    role: "DENTIST",
    title: "Oral Surgeon",
    specialty: "Oral Surgery",
    email: "david.surgery@brightsmile.co.ke",
    phone: "+254 712 345 005",
    experienceYears: 12,
    rating: 4.6,
    reviews: 143,
    status: "ON_LEAVE",
    department: "Clinical",
    avatarTone: "bg-warning-soft text-warning-foreground",
    initials: "DO",
  },
  {
    id: "STF-006",
    name: "Sarah Wanjiku",
    role: "RECEPTIONIST",
    title: "Senior Receptionist",
    email: "sarah.wanjiku@brightsmile.co.ke",
    phone: "+254 712 345 006",
    status: "AVAILABLE",
    department: "Front Office",
    avatarTone: "bg-brand-soft text-brand",
    initials: "SW",
  },
  {
    id: "STF-007",
    name: "Alice Wanjiku",
    role: "RECEPTIONIST",
    title: "Receptionist",
    email: "alice.wanjiku@brightsmile.co.ke",
    phone: "+254 712 345 007",
    status: "AVAILABLE",
    department: "Front Office",
    avatarTone: "bg-brand-soft text-brand",
    initials: "AW",
  },
  {
    id: "STF-008",
    name: "David Ochieng",
    role: "ACCOUNTANT",
    title: "Accountant",
    email: "david.ochieng@brightsmile.co.ke",
    phone: "+254 712 345 008",
    status: "AVAILABLE",
    department: "Finance",
    avatarTone: "bg-success-soft text-success",
    initials: "DO",
  },
  {
    id: "STF-009",
    name: "Dr. Mwangi",
    role: "ADMIN",
    title: "Administrator",
    email: "admin@brightsmile.co.ke",
    phone: "+254 712 345 009",
    status: "AVAILABLE",
    department: "Management",
    avatarTone: "bg-navy text-primary-foreground",
    initials: "DM",
  },
  {
    id: "STF-010",
    name: "Admin",
    role: "SUPER_ADMIN",
    title: "Super Admin",
    email: "superadmin@brightsmile.co.ke",
    phone: "+254 712 345 010",
    status: "AVAILABLE",
    department: "Management",
    avatarTone: "bg-navy text-primary-foreground",
    initials: "SA",
  },
  {
    id: "STF-011",
    name: "Esther Njoroge",
    role: "NURSE",
    title: "Dental Nurse",
    email: "esther.njoroge@brightsmile.co.ke",
    phone: "+254 712 345 011",
    status: "AVAILABLE",
    department: "Clinical",
    avatarTone: "bg-teal-soft text-teal",
    initials: "EN",
  },
  {
    id: "STF-012",
    name: "Brian Kiptoo",
    role: "LAB_TECHNICIAN",
    title: "Laboratory Technician",
    email: "brian.kiptoo@brightsmile.co.ke",
    phone: "+254 712 345 012",
    status: "AVAILABLE",
    department: "Laboratory",
    avatarTone: "bg-violet-soft text-violet",
    initials: "BK",
  },
];

export const dentists = staff.filter((member) => member.role === "DENTIST");

export const patients: Patient[] = [
  {
    id: "PAT-001",
    code: "PAT-2026-0002",
    name: "Mary Wanjiku",
    phone: "0723 456 789",
    email: "mary.wanjiku@example.co.ke",
    gender: "Female",
    dateOfBirth: "1991-04-18",
    town: "Kerugoya",
    registeredOn: "2024-02-11",
    lastVisit: "2025-09-20",
    status: "Active",
    allergies: ["Penicillin"],
    conditions: [],
    bloodGroup: "O+",
    initials: "MW",
    avatarTone: "bg-brand-soft text-brand",
  },
  {
    id: "PAT-002",
    code: "PAT-2026-0003",
    name: "John K. Mutiso",
    phone: "0711 234 567",
    email: "john.mutiso@example.co.ke",
    gender: "Male",
    dateOfBirth: "1986-11-02",
    town: "Kutus",
    registeredOn: "2023-08-30",
    lastVisit: "2025-09-18",
    status: "Active",
    allergies: [],
    conditions: ["Hypertension"],
    bloodGroup: "A+",
    initials: "JM",
    avatarTone: "bg-info-soft text-info",
  },
  {
    id: "PAT-003",
    code: "PAT-2026-0004",
    name: "Grace Njeri",
    phone: "0708 987 654",
    email: "grace.njeri@example.co.ke",
    gender: "Female",
    dateOfBirth: "2004-06-21",
    town: "Kerugoya",
    registeredOn: "2024-10-05",
    lastVisit: "2025-09-15",
    status: "Active",
    allergies: ["Latex"],
    conditions: [],
    bloodGroup: "B+",
    initials: "GN",
    avatarTone: "bg-violet-soft text-violet",
  },
  {
    id: "PAT-004",
    code: "PAT-2026-0005",
    name: "David Ochieng",
    phone: "0722 345 678",
    email: "david.patient@example.co.ke",
    gender: "Male",
    dateOfBirth: "1979-01-14",
    town: "Kagio",
    registeredOn: "2022-05-19",
    lastVisit: "2025-09-10",
    status: "Active",
    allergies: [],
    conditions: ["Diabetes Type 2"],
    bloodGroup: "O-",
    initials: "DO",
    avatarTone: "bg-success-soft text-success",
  },
  {
    id: "PAT-005",
    code: "PAT-2026-0001",
    name: "Amina Wanjiku",
    phone: "0710 876 543",
    email: "amina.wanjiku@example.co.ke",
    gender: "Female",
    dateOfBirth: "1995-09-08",
    town: "Kerugoya",
    registeredOn: "2023-01-24",
    lastVisit: "2025-09-08",
    status: "Active",
    allergies: ["Ibuprofen"],
    conditions: [],
    bloodGroup: "AB+",
    initials: "AW",
    avatarTone: "bg-teal-soft text-teal",
  },
  {
    id: "PAT-006",
    code: "PAT-2026-0006",
    name: "Peter Kamau",
    phone: "0733 221 554",
    email: "peter.kamau@example.co.ke",
    gender: "Male",
    dateOfBirth: "1998-03-30",
    town: "Sagana",
    registeredOn: "2025-03-02",
    lastVisit: "2025-09-06",
    status: "Active",
    allergies: [],
    conditions: [],
    bloodGroup: "A-",
    initials: "PK",
    avatarTone: "bg-warning-soft text-warning-foreground",
  },
  {
    id: "PAT-007",
    code: "PAT-2026-0007",
    name: "Faith Njeri",
    phone: "0745 118 220",
    email: "faith.njeri@example.co.ke",
    gender: "Female",
    dateOfBirth: "2009-12-12",
    town: "Kerugoya",
    registeredOn: "2025-06-14",
    lastVisit: "2025-09-02",
    status: "Active",
    allergies: [],
    conditions: [],
    bloodGroup: "O+",
    initials: "FN",
    avatarTone: "bg-brand-soft text-brand",
  },
  {
    id: "PAT-008",
    code: "PAT-2026-0008",
    name: "James Manyala",
    phone: "0799 442 110",
    email: "james.manyala@example.co.ke",
    gender: "Male",
    dateOfBirth: "1983-07-07",
    town: "Kutus",
    registeredOn: "2024-11-21",
    lastVisit: "2025-08-29",
    status: "Active",
    allergies: [],
    conditions: [],
    bloodGroup: "B-",
    initials: "JM",
    avatarTone: "bg-info-soft text-info",
  },
];

export const services: Service[] = [
  { id: "SRV-01", name: "General Check-up", category: "General Dentistry", price: 1500, durationMinutes: 30 },
  { id: "SRV-02", name: "Teeth Cleaning", category: "General Dentistry", price: 3500, durationMinutes: 45 },
  { id: "SRV-03", name: "Orthodontic Consultation", category: "Orthodontics", price: 4200, durationMinutes: 45 },
  { id: "SRV-04", name: "Filling", category: "Restorative Dentistry", price: 5800, durationMinutes: 60 },
  { id: "SRV-05", name: "Cosmetic Consultation", category: "Cosmetic Dentistry", price: 3000, durationMinutes: 30 },
  { id: "SRV-06", name: "Root Canal Treatment", category: "Restorative Dentistry", price: 12500, durationMinutes: 90 },
  { id: "SRV-07", name: "Braces Adjustment", category: "Orthodontics", price: 4500, durationMinutes: 40 },
  { id: "SRV-08", name: "Teeth Whitening", category: "Cosmetic Dentistry", price: 9500, durationMinutes: 60 },
];

export const appointments: Appointment[] = [
  {
    id: "APT-1001",
    patientId: "PAT-001",
    dentistId: "STF-002",
    serviceId: "SRV-01",
    date: DEMO_TODAY,
    time: "08:30 AM",
    endTime: "09:00 AM",
    status: "IN_ROOM",
    createdBy: "STF-006",
  },
  {
    id: "APT-1002",
    patientId: "PAT-002",
    dentistId: "STF-001",
    serviceId: "SRV-02",
    date: DEMO_TODAY,
    time: "09:30 AM",
    endTime: "10:15 AM",
    status: "WAITING",
    createdBy: "STF-006",
  },
  {
    id: "APT-1003",
    patientId: "PAT-003",
    dentistId: "STF-004",
    serviceId: "SRV-03",
    date: DEMO_TODAY,
    time: "10:30 AM",
    endTime: "11:15 AM",
    status: "CHECKED_IN",
    createdBy: "STF-007",
  },
  {
    id: "APT-1004",
    patientId: "PAT-004",
    dentistId: "STF-003",
    serviceId: "SRV-04",
    date: DEMO_TODAY,
    time: "11:30 AM",
    endTime: "12:30 PM",
    status: "SCHEDULED",
    createdBy: "STF-007",
  },
  {
    id: "APT-1005",
    patientId: "PAT-005",
    dentistId: "STF-002",
    serviceId: "SRV-05",
    date: DEMO_TODAY,
    time: "01:00 PM",
    endTime: "01:30 PM",
    status: "SCHEDULED",
    createdBy: "STF-006",
  },
  {
    id: "APT-1006",
    patientId: "PAT-006",
    dentistId: "STF-001",
    serviceId: "SRV-06",
    date: DEMO_TODAY,
    time: "02:30 PM",
    endTime: "04:00 PM",
    status: "SCHEDULED",
    createdBy: "STF-006",
  },
  {
    id: "APT-1007",
    patientId: "PAT-007",
    dentistId: "STF-004",
    serviceId: "SRV-07",
    date: DEMO_TODAY,
    time: "04:00 PM",
    endTime: "04:40 PM",
    status: "CONFIRMED",
    createdBy: "STF-007",
  },
  {
    id: "APT-1008",
    patientId: "PAT-008",
    dentistId: "STF-001",
    serviceId: "SRV-01",
    date: DEMO_TODAY,
    time: "04:30 PM",
    endTime: "05:00 PM",
    status: "SCHEDULED",
    createdBy: "STF-007",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-01",
    number: "INV-2025-0147",
    patientId: "PAT-001",
    date: "2025-09-20",
    dueDate: "2025-09-22",
    items: [{ description: "Teeth Cleaning", quantity: 1, unitPrice: 3500 }],
    status: "PAID",
    amountPaid: 3500,
  },
  {
    id: "INV-02",
    number: "INV-2025-0146",
    patientId: "PAT-002",
    date: "2025-09-19",
    dueDate: "2025-09-25",
    items: [{ description: "Filling", quantity: 1, unitPrice: 5800 }],
    status: "PAID",
    amountPaid: 5800,
  },
  {
    id: "INV-03",
    number: "INV-2025-0145",
    patientId: "PAT-003",
    date: "2025-09-18",
    dueDate: "2025-09-28",
    items: [{ description: "Orthodontic Consultation", quantity: 1, unitPrice: 4200 }],
    status: "PENDING",
    amountPaid: 0,
  },
  {
    id: "INV-04",
    number: "INV-2025-0144",
    patientId: "PAT-004",
    date: "2025-09-17",
    dueDate: "2025-09-27",
    items: [{ description: "Root Canal (session 1)", quantity: 1, unitPrice: 7500 }],
    status: "PAID",
    amountPaid: 7500,
  },
  {
    id: "INV-05",
    number: "INV-2025-0143",
    patientId: "PAT-005",
    date: "2025-09-16",
    dueDate: "2025-09-19",
    items: [{ description: "Cosmetic Consultation", quantity: 1, unitPrice: 3000 }, { description: "Whitening deposit", quantity: 1, unitPrice: 3300 }],
    status: "OVERDUE",
    amountPaid: 0,
  },
];

export const payments: Payment[] = [
  { id: "PMT-01", invoiceNumber: "INV-2025-0147", patientId: "PAT-001", date: "2025-09-20", amount: 3500, method: "M-Pesa", reference: "SJK4TY9A1" },
  { id: "PMT-02", invoiceNumber: "INV-2025-0146", patientId: "PAT-002", date: "2025-09-19", amount: 5800, method: "Cash", reference: "RCPT-0922" },
  { id: "PMT-03", invoiceNumber: "INV-2025-0144", patientId: "PAT-004", date: "2025-09-17", amount: 7500, method: "Bank", reference: "KCB-88213" },
];

export const transactions: Transaction[] = [
  { id: "TRX-01", date: "2025-09-20", description: "Patient Payment", type: "Income", amount: 3500, account: "M-Pesa Account" },
  { id: "TRX-02", date: "2025-09-19", description: "Supplies Purchase", type: "Expense", amount: 12000, account: "Bank Account (KCB)" },
  { id: "TRX-03", date: "2025-09-18", description: "M-Pesa Deposit", type: "Income", amount: 8000, account: "M-Pesa Account" },
  { id: "TRX-04", date: "2025-09-17", description: "Equipment Service", type: "Expense", amount: 15600, account: "Bank Account (KCB)" },
  { id: "TRX-05", date: "2025-09-16", description: "Patient Payment", type: "Income", amount: 4200, account: "Cash Account" },
  { id: "TRX-06", date: "2025-09-15", description: "Rent Payment", type: "Expense", amount: 80000, account: "Bank Account (KCB)" },
];

export const expenseBreakdown: ExpenseCategory[] = [
  { name: "Salaries & Wages", share: 34, tone: "var(--chart-1)" },
  { name: "Supplies & Materials", share: 22, tone: "var(--chart-2)" },
  { name: "Utilities", share: 12, tone: "var(--chart-5)" },
  { name: "Equipment", share: 10, tone: "var(--chart-3)" },
  { name: "Rent & Facilities", share: 8, tone: "var(--chart-4)" },
  { name: "Other", share: 14, tone: "var(--chart-6)" },
];

export const accountBalances: AccountBalance[] = [
  { name: "Cash Account", balance: 102450, icon: "cash" },
  { name: "M-Pesa Account", balance: 68320, icon: "mobile" },
  { name: "Bank Account (KCB)", balance: 312880, icon: "bank" },
  { name: "Petty Cash", balance: 5000, icon: "petty" },
];

export const revenueVsExpenses: TrendPoint[] = [
  { label: "Sep 14", revenue: 420000, expenses: 300000 },
  { label: "Sep 15", revenue: 385000, expenses: 268000 },
  { label: "Sep 16", revenue: 520000, expenses: 342000 },
  { label: "Sep 17", revenue: 455000, expenses: 305000 },
  { label: "Sep 18", revenue: 610000, expenses: 360000 },
  { label: "Sep 19", revenue: 598000, expenses: 388000 },
  { label: "Sep 20", revenue: 742580, expenses: 452000 },
];

export const appointmentsOverview: TrendPoint[] = [
  { label: "Sep 14", completed: 6, scheduled: 9, cancelled: 1 },
  { label: "Sep 15", completed: 5, scheduled: 11, cancelled: 0 },
  { label: "Sep 16", completed: 7, scheduled: 8, cancelled: 1 },
  { label: "Sep 17", completed: 6, scheduled: 10, cancelled: 0 },
  { label: "Sep 18", completed: 5, scheduled: 9, cancelled: 0 },
  { label: "Sep 19", completed: 7, scheduled: 11, cancelled: 0 },
  { label: "Sep 20", completed: 6, scheduled: 12, cancelled: 0 },
];

export const adminAppointmentsOverview: TrendPoint[] = [
  { label: "Mon 15", completed: 22, scheduled: 14, cancelled: 3 },
  { label: "Tue 16", completed: 25, scheduled: 18, cancelled: 2 },
  { label: "Wed 17", completed: 21, scheduled: 16, cancelled: 4 },
  { label: "Thu 18", completed: 27, scheduled: 20, cancelled: 3 },
  { label: "Fri 19", completed: 24, scheduled: 19, cancelled: 2 },
  { label: "Sat 20", completed: 32, scheduled: 28, cancelled: 4 },
  { label: "Sun 21", completed: 26, scheduled: 22, cancelled: 3 },
];

export const monthlyRevenue: TrendPoint[] = [
  { label: "Jan", revenue: 142000 },
  { label: "Feb", revenue: 156000 },
  { label: "Mar", revenue: 168000 },
  { label: "Apr", revenue: 158000 },
  { label: "May", revenue: 182000 },
  { label: "Jun", revenue: 176000 },
  { label: "Jul", revenue: 205000 },
  { label: "Aug", revenue: 224000 },
  { label: "Sep", revenue: 245680 },
];

export const patientsByService = [
  { name: "General Dentistry", share: 32, tone: "var(--chart-1)" },
  { name: "Cosmetic Dentistry", share: 24, tone: "var(--chart-2)" },
  { name: "Orthodontics", share: 18, tone: "var(--chart-3)" },
  { name: "Restorative Dentistry", share: 15, tone: "var(--chart-4)" },
  { name: "Oral Surgery", share: 7, tone: "var(--chart-5)" },
  { name: "Others", share: 4, tone: "var(--chart-6)" },
];

export const dentistDemographics = [
  { name: "General Dentistry", share: 34, tone: "var(--chart-1)" },
  { name: "Cosmetic Dentistry", share: 26, tone: "var(--chart-2)" },
  { name: "Orthodontics", share: 15, tone: "var(--chart-3)" },
  { name: "Restorative Dentistry", share: 12, tone: "var(--chart-4)" },
  { name: "Oral Surgery", share: 8, tone: "var(--chart-5)" },
  { name: "Others", share: 5, tone: "var(--chart-6)" },
];

export const contentOverview: TrendPoint[] = [
  { label: "Apr 2025", articles: 6, events: 3, campaigns: 1 },
  { label: "May 2025", articles: 8, events: 4, campaigns: 2 },
  { label: "Jun 2025", articles: 11, events: 5, campaigns: 2 },
  { label: "Jul 2025", articles: 12, events: 6, campaigns: 3 },
  { label: "Aug 2025", articles: 16, events: 8, campaigns: 4 },
  { label: "Sep 2025", articles: 18, events: 11, campaigns: 6 },
];

export const activities: ActivityEntry[] = [
  { id: "ACT-1", time: "08:25 AM", message: "Mary Wanjiku checked in", detail: "General Check-up", tone: "bg-success-soft text-success" },
  { id: "ACT-2", time: "08:15 AM", message: "Payment received (KSh 3,500)", detail: "John K. Mutiso", tone: "bg-brand-soft text-brand" },
  { id: "ACT-3", time: "07:50 AM", message: "New appointment booked", detail: "Grace Njeri", tone: "bg-violet-soft text-violet" },
  { id: "ACT-4", time: "07:32 AM", message: "Prescription issued", detail: "David Ochieng", tone: "bg-teal-soft text-teal" },
  { id: "ACT-5", time: "07:15 AM", message: "Message from Dr. Sarah Kimani", detail: "Aisha Wanjiru", tone: "bg-warning-soft text-warning-foreground" },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "NEWS-1",
    tag: "HEALTH TIPS",
    title: "5 Daily Habits for a Healthier Smile",
    date: "Sep 18, 2025",
    excerpt:
      "Small daily habits make a big difference to your oral health. Here are five simple ways to keep your smile bright between visits.",
  },
  {
    id: "NEWS-2",
    tag: "CLINIC NEWS",
    title: "Our New Dental Laser Technology",
    date: "Sep 12, 2025",
    excerpt:
      "We are excited to introduce our new dental laser technology, offering safer, faster and more comfortable treatments for our patients.",
  },
  {
    id: "NEWS-3",
    tag: "COMMUNITY",
    title: "Free Dental Camp at Kerugoya",
    date: "Sep 5, 2025",
    excerpt:
      "Our team visited Kerugoya Primary School for a free dental camp, providing check-ups, fluoride treatments and oral hygiene education.",
  },
];

export const clinicEvents: ClinicEvent[] = [
  {
    id: "EVT-1",
    title: "Oral Health Awareness Talk",
    monthLabel: "OCT",
    day: "12",
    year: "2025",
    date: "Oct 12, 2025",
    timeRange: "10:00 AM – 12:00 PM",
    location: "BrightSmile Clinic",
    fee: "Free",
    registrations: 42,
    capacity: 100,
  },
  {
    id: "EVT-2",
    title: "Children's Dental Check-up Day",
    monthLabel: "OCT",
    day: "26",
    year: "2025",
    date: "Oct 26, 2025",
    timeRange: "9:00 AM – 2:00 PM",
    location: "BrightSmile Clinic",
    fee: "Free",
    registrations: 78,
    capacity: 100,
  },
  {
    id: "EVT-3",
    title: "Orthodontic Consultation Day",
    monthLabel: "NOV",
    day: "15",
    year: "2025",
    date: "Nov 15, 2025",
    timeRange: "9:00 AM – 4:00 PM",
    location: "BrightSmile Clinic",
    fee: "KSh 1,000",
    registrations: 25,
    capacity: 50,
  },
  {
    id: "EVT-4",
    title: "Free Dental Camp",
    monthLabel: "DEC",
    day: "5",
    year: "2025",
    date: "Dec 5, 2025",
    timeRange: "8:00 AM – 4:00 PM",
    location: "Kerugoya Grounds",
    fee: "Free",
    registrations: 120,
    capacity: 200,
  },
];

export const campaigns: Campaign[] = [
  {
    id: "CMP-1",
    title: "Brighter Smiles Tomorrow",
    blurb: "Get 20% off on Teeth Whitening this month!",
    period: "Sep 1, 2025 – Sep 30, 2025",
    badge: "20% OFF",
    state: "Active",
  },
  {
    id: "CMP-2",
    title: "Healthy Smiles for All",
    blurb: "Get a free dental check-up and consultation this month.",
    period: "Sep 10, 2025 – Oct 31, 2025",
    badge: "FREE CHECK-UP",
    state: "Active",
  },
  {
    id: "CMP-3",
    title: "Children's Dental Care",
    blurb: "Gentle care and fluoride protection for young smiles.",
    period: "Oct 1, 2025 – Nov 30, 2025",
    badge: "KIDS",
    state: "Scheduled",
  },
];
