/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceRoleRouteImport } from './routes/workspace.$role'
import { Route as WorkspaceRoleIndexRouteImport } from './routes/workspace.$role.index'
import { Route as WorkspaceRoleModuleRouteImport } from './routes/workspace.$role.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoleRoute = WorkspaceRoleRouteImport.update({
  id: '/workspace/$role',
  path: '/workspace/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoleIndexRoute = WorkspaceRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoleRoute,
} as any)
const WorkspaceRoleModuleRoute = WorkspaceRoleModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => WorkspaceRoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/workspace/$role': typeof WorkspaceRoleRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$role/$module': typeof WorkspaceRoleModuleRoute
  '/workspace/$role/': typeof WorkspaceRoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/$role/$module': typeof WorkspaceRoleModuleRoute
  '/workspace/$role': typeof WorkspaceRoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/workspace/$role': typeof WorkspaceRoleRouteWithChildren
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$role/$module': typeof WorkspaceRoleModuleRoute
  '/workspace/$role/': typeof WorkspaceRoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/services'
    | '/team'
    | '/workspace/$role'
    | '/workspace/'
    | '/workspace/$role/$module'
    | '/workspace/$role/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/services'
    | '/team'
    | '/workspace'
    | '/workspace/$role/$module'
    | '/workspace/$role'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/booking'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/login'
    | '/services'
    | '/team'
    | '/workspace/$role'
    | '/workspace/'
    | '/workspace/$role/$module'
    | '/workspace/$role/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  WorkspaceRoleRoute: typeof WorkspaceRoleRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$role': {
      id: '/workspace/$role'
      path: '/workspace/$role'
      fullPath: '/workspace/$role'
      preLoaderRoute: typeof WorkspaceRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$role/': {
      id: '/workspace/$role/'
      path: '/'
      fullPath: '/workspace/$role/'
      preLoaderRoute: typeof WorkspaceRoleIndexRouteImport
      parentRoute: typeof WorkspaceRoleRoute
    }
    '/workspace/$role/$module': {
      id: '/workspace/$role/$module'
      path: '/$module'
      fullPath: '/workspace/$role/$module'
      preLoaderRoute: typeof WorkspaceRoleModuleRouteImport
      parentRoute: typeof WorkspaceRoleRoute
    }
  }
}

interface WorkspaceRoleRouteChildren {
  WorkspaceRoleModuleRoute: typeof WorkspaceRoleModuleRoute
  WorkspaceRoleIndexRoute: typeof WorkspaceRoleIndexRoute
}

const WorkspaceRoleRouteChildren: WorkspaceRoleRouteChildren = {
  WorkspaceRoleModuleRoute: WorkspaceRoleModuleRoute,
  WorkspaceRoleIndexRoute: WorkspaceRoleIndexRoute,
}

const WorkspaceRoleRouteWithChildren = WorkspaceRoleRoute._addFileChildren(
  WorkspaceRoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  WorkspaceRoleRoute: WorkspaceRoleRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
